/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardSplatRouteImport } from './routes/_dashboard/$'
import { Route as DashboardWorkspaceRouteImport } from './routes/_dashboard/_workspace'
import { Route as DashboardOnboardingRouteImport } from './routes/_dashboard/onboarding'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSquadsRouteImport } from './routes/_dashboard/squads'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as HandlerSplatRouteImport } from './routes/handler.$'
import { Route as DashboardWorkspaceEmployeesRouteImport } from './routes/_dashboard/_workspace/employees'
import { Route as DashboardWorkspaceOverviewRouteImport } from './routes/_dashboard/_workspace/overview'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSquadsRoute = DashboardSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const HandlerSplatRoute = HandlerSplatRouteImport.update({
  id: '/handler/$',
  path: '/handler/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceEmployeesRoute =
  DashboardWorkspaceEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => DashboardWorkspaceRoute,
  } as any)
const DashboardWorkspaceOverviewRoute =
  DashboardWorkspaceOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof DashboardSplatRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/settings': typeof DashboardSettingsRoute
  '/squads': typeof DashboardSquadsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/employees': typeof DashboardWorkspaceEmployeesRoute
  '/overview': typeof DashboardWorkspaceOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof DashboardSplatRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/settings': typeof DashboardSettingsRoute
  '/squads': typeof DashboardSquadsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/employees': typeof DashboardWorkspaceEmployeesRoute
  '/overview': typeof DashboardWorkspaceOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_dashboard/$': typeof DashboardSplatRoute
  '/_dashboard/_workspace': typeof DashboardWorkspaceRouteWithChildren
  '/_dashboard/onboarding': typeof DashboardOnboardingRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/squads': typeof DashboardSquadsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_dashboard/_workspace/employees': typeof DashboardWorkspaceEmployeesRoute
  '/_dashboard/_workspace/overview': typeof DashboardWorkspaceOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/$'
    | '/onboarding'
    | '/settings'
    | '/squads'
    | '/handler/$'
    | '/employees'
    | '/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/$'
    | '/onboarding'
    | '/settings'
    | '/squads'
    | '/handler/$'
    | '/employees'
    | '/overview'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_marketing'
    | '/sign-in'
    | '/_dashboard/$'
    | '/_dashboard/_workspace'
    | '/_dashboard/onboarding'
    | '/_dashboard/settings'
    | '/_dashboard/squads'
    | '/handler/$'
    | '/_marketing/'
    | '/_dashboard/_workspace/employees'
    | '/_dashboard/_workspace/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  SignInRoute: typeof SignInRoute
  HandlerSplatRoute: typeof HandlerSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$': {
      id: '/_dashboard/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_workspace': {
      id: '/_dashboard/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/onboarding': {
      id: '/_dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/squads': {
      id: '/_dashboard/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof DashboardSquadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/handler/$': {
      id: '/handler/$'
      path: '/handler/$'
      fullPath: '/handler/$'
      preLoaderRoute: typeof HandlerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_workspace/employees': {
      id: '/_dashboard/_workspace/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardWorkspaceEmployeesRouteImport
      parentRoute: typeof DashboardWorkspaceRoute
    }
    '/_dashboard/_workspace/overview': {
      id: '/_dashboard/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardWorkspaceOverviewRouteImport
      parentRoute: typeof DashboardWorkspaceRoute
    }
  }
}

interface DashboardWorkspaceRouteChildren {
  DashboardWorkspaceEmployeesRoute: typeof DashboardWorkspaceEmployeesRoute
  DashboardWorkspaceOverviewRoute: typeof DashboardWorkspaceOverviewRoute
}

const DashboardWorkspaceRouteChildren: DashboardWorkspaceRouteChildren = {
  DashboardWorkspaceEmployeesRoute: DashboardWorkspaceEmployeesRoute,
  DashboardWorkspaceOverviewRoute: DashboardWorkspaceOverviewRoute,
}

const DashboardWorkspaceRouteWithChildren =
  DashboardWorkspaceRoute._addFileChildren(DashboardWorkspaceRouteChildren)

interface DashboardRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRouteWithChildren
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSquadsRoute: typeof DashboardSquadsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRouteWithChildren,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSquadsRoute: DashboardSquadsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  SignInRoute: SignInRoute,
  HandlerSplatRoute: HandlerSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
