/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardSplatRouteImport } from './routes/_dashboard/$'
import { Route as DashboardWorkspaceRouteImport } from './routes/_dashboard/_workspace'
import { Route as DashboardOnboardingRouteImport } from './routes/_dashboard/onboarding'
import { Route as DashboardProspectsRouteImport } from './routes/_dashboard/prospects'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as HandlerSplatRouteImport } from './routes/handler.$'
import { Route as DashboardWorkspaceInboxRouteImport } from './routes/_dashboard/_workspace/inbox'
import { Route as DashboardWorkspaceLeadsRouteImport } from './routes/_dashboard/_workspace/leads'
import { Route as DashboardWorkspaceOverviewRouteImport } from './routes/_dashboard/_workspace/overview'
import { Route as DashboardWorkspaceInboxIndexRouteImport } from './routes/_dashboard/_workspace/inbox/index'
import { Route as DashboardWorkspaceInboxConversationIdRouteImport } from './routes/_dashboard/_workspace/inbox/$conversationId'
import { Route as DashboardWorkspaceLeadsIndexRouteImport } from './routes/_dashboard/_workspace/leads/index'
import { Route as DashboardWorkspaceOverviewIndexRouteImport } from './routes/_dashboard/_workspace/overview/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProspectsRoute = DashboardProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const HandlerSplatRoute = HandlerSplatRouteImport.update({
  id: '/handler/$',
  path: '/handler/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceInboxRoute = DashboardWorkspaceInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardWorkspaceRoute,
} as any)
const DashboardWorkspaceLeadsRoute = DashboardWorkspaceLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardWorkspaceRoute,
} as any)
const DashboardWorkspaceOverviewRoute =
  DashboardWorkspaceOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardWorkspaceRoute,
  } as any)
const DashboardWorkspaceInboxIndexRoute =
  DashboardWorkspaceInboxIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceInboxRoute,
  } as any)
const DashboardWorkspaceInboxConversationIdRoute =
  DashboardWorkspaceInboxConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => DashboardWorkspaceInboxRoute,
  } as any)
const DashboardWorkspaceLeadsIndexRoute =
  DashboardWorkspaceLeadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceLeadsRoute,
  } as any)
const DashboardWorkspaceOverviewIndexRoute =
  DashboardWorkspaceOverviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceOverviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof DashboardSplatRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/prospects': typeof DashboardProspectsRoute
  '/settings': typeof DashboardSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/inbox': typeof DashboardWorkspaceInboxRouteWithChildren
  '/leads': typeof DashboardWorkspaceLeadsRouteWithChildren
  '/overview': typeof DashboardWorkspaceOverviewRouteWithChildren
  '/inbox/$conversationId': typeof DashboardWorkspaceInboxConversationIdRoute
  '/inbox/': typeof DashboardWorkspaceInboxIndexRoute
  '/leads/': typeof DashboardWorkspaceLeadsIndexRoute
  '/overview/': typeof DashboardWorkspaceOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof DashboardSplatRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/prospects': typeof DashboardProspectsRoute
  '/settings': typeof DashboardSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/inbox/$conversationId': typeof DashboardWorkspaceInboxConversationIdRoute
  '/inbox': typeof DashboardWorkspaceInboxIndexRoute
  '/leads': typeof DashboardWorkspaceLeadsIndexRoute
  '/overview': typeof DashboardWorkspaceOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_dashboard/$': typeof DashboardSplatRoute
  '/_dashboard/_workspace': typeof DashboardWorkspaceRouteWithChildren
  '/_dashboard/onboarding': typeof DashboardOnboardingRoute
  '/_dashboard/prospects': typeof DashboardProspectsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/handler/$': typeof HandlerSplatRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_dashboard/_workspace/inbox': typeof DashboardWorkspaceInboxRouteWithChildren
  '/_dashboard/_workspace/leads': typeof DashboardWorkspaceLeadsRouteWithChildren
  '/_dashboard/_workspace/overview': typeof DashboardWorkspaceOverviewRouteWithChildren
  '/_dashboard/_workspace/inbox/$conversationId': typeof DashboardWorkspaceInboxConversationIdRoute
  '/_dashboard/_workspace/inbox/': typeof DashboardWorkspaceInboxIndexRoute
  '/_dashboard/_workspace/leads/': typeof DashboardWorkspaceLeadsIndexRoute
  '/_dashboard/_workspace/overview/': typeof DashboardWorkspaceOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/$'
    | '/onboarding'
    | '/prospects'
    | '/settings'
    | '/handler/$'
    | '/inbox'
    | '/leads'
    | '/overview'
    | '/inbox/$conversationId'
    | '/inbox/'
    | '/leads/'
    | '/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/$'
    | '/onboarding'
    | '/prospects'
    | '/settings'
    | '/handler/$'
    | '/inbox/$conversationId'
    | '/inbox'
    | '/leads'
    | '/overview'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_marketing'
    | '/sign-in'
    | '/_dashboard/$'
    | '/_dashboard/_workspace'
    | '/_dashboard/onboarding'
    | '/_dashboard/prospects'
    | '/_dashboard/settings'
    | '/handler/$'
    | '/_marketing/'
    | '/_dashboard/_workspace/inbox'
    | '/_dashboard/_workspace/leads'
    | '/_dashboard/_workspace/overview'
    | '/_dashboard/_workspace/inbox/$conversationId'
    | '/_dashboard/_workspace/inbox/'
    | '/_dashboard/_workspace/leads/'
    | '/_dashboard/_workspace/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  SignInRoute: typeof SignInRoute
  HandlerSplatRoute: typeof HandlerSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$': {
      id: '/_dashboard/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_workspace': {
      id: '/_dashboard/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/onboarding': {
      id: '/_dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/prospects': {
      id: '/_dashboard/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof DashboardProspectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/handler/$': {
      id: '/handler/$'
      path: '/handler/$'
      fullPath: '/handler/$'
      preLoaderRoute: typeof HandlerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_workspace/inbox': {
      id: '/_dashboard/_workspace/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof DashboardWorkspaceInboxRouteImport
      parentRoute: typeof DashboardWorkspaceRoute
    }
    '/_dashboard/_workspace/leads': {
      id: '/_dashboard/_workspace/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof DashboardWorkspaceLeadsRouteImport
      parentRoute: typeof DashboardWorkspaceRoute
    }
    '/_dashboard/_workspace/overview': {
      id: '/_dashboard/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardWorkspaceOverviewRouteImport
      parentRoute: typeof DashboardWorkspaceRoute
    }
    '/_dashboard/_workspace/inbox/': {
      id: '/_dashboard/_workspace/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof DashboardWorkspaceInboxIndexRouteImport
      parentRoute: typeof DashboardWorkspaceInboxRoute
    }
    '/_dashboard/_workspace/inbox/$conversationId': {
      id: '/_dashboard/_workspace/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof DashboardWorkspaceInboxConversationIdRouteImport
      parentRoute: typeof DashboardWorkspaceInboxRoute
    }
    '/_dashboard/_workspace/leads/': {
      id: '/_dashboard/_workspace/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof DashboardWorkspaceLeadsIndexRouteImport
      parentRoute: typeof DashboardWorkspaceLeadsRoute
    }
    '/_dashboard/_workspace/overview/': {
      id: '/_dashboard/_workspace/overview/'
      path: '/'
      fullPath: '/overview/'
      preLoaderRoute: typeof DashboardWorkspaceOverviewIndexRouteImport
      parentRoute: typeof DashboardWorkspaceOverviewRoute
    }
  }
}

interface DashboardWorkspaceInboxRouteChildren {
  DashboardWorkspaceInboxConversationIdRoute: typeof DashboardWorkspaceInboxConversationIdRoute
  DashboardWorkspaceInboxIndexRoute: typeof DashboardWorkspaceInboxIndexRoute
}

const DashboardWorkspaceInboxRouteChildren: DashboardWorkspaceInboxRouteChildren =
  {
    DashboardWorkspaceInboxConversationIdRoute:
      DashboardWorkspaceInboxConversationIdRoute,
    DashboardWorkspaceInboxIndexRoute: DashboardWorkspaceInboxIndexRoute,
  }

const DashboardWorkspaceInboxRouteWithChildren =
  DashboardWorkspaceInboxRoute._addFileChildren(
    DashboardWorkspaceInboxRouteChildren,
  )

interface DashboardWorkspaceLeadsRouteChildren {
  DashboardWorkspaceLeadsIndexRoute: typeof DashboardWorkspaceLeadsIndexRoute
}

const DashboardWorkspaceLeadsRouteChildren: DashboardWorkspaceLeadsRouteChildren =
  {
    DashboardWorkspaceLeadsIndexRoute: DashboardWorkspaceLeadsIndexRoute,
  }

const DashboardWorkspaceLeadsRouteWithChildren =
  DashboardWorkspaceLeadsRoute._addFileChildren(
    DashboardWorkspaceLeadsRouteChildren,
  )

interface DashboardWorkspaceOverviewRouteChildren {
  DashboardWorkspaceOverviewIndexRoute: typeof DashboardWorkspaceOverviewIndexRoute
}

const DashboardWorkspaceOverviewRouteChildren: DashboardWorkspaceOverviewRouteChildren =
  {
    DashboardWorkspaceOverviewIndexRoute: DashboardWorkspaceOverviewIndexRoute,
  }

const DashboardWorkspaceOverviewRouteWithChildren =
  DashboardWorkspaceOverviewRoute._addFileChildren(
    DashboardWorkspaceOverviewRouteChildren,
  )

interface DashboardWorkspaceRouteChildren {
  DashboardWorkspaceInboxRoute: typeof DashboardWorkspaceInboxRouteWithChildren
  DashboardWorkspaceLeadsRoute: typeof DashboardWorkspaceLeadsRouteWithChildren
  DashboardWorkspaceOverviewRoute: typeof DashboardWorkspaceOverviewRouteWithChildren
}

const DashboardWorkspaceRouteChildren: DashboardWorkspaceRouteChildren = {
  DashboardWorkspaceInboxRoute: DashboardWorkspaceInboxRouteWithChildren,
  DashboardWorkspaceLeadsRoute: DashboardWorkspaceLeadsRouteWithChildren,
  DashboardWorkspaceOverviewRoute: DashboardWorkspaceOverviewRouteWithChildren,
}

const DashboardWorkspaceRouteWithChildren =
  DashboardWorkspaceRoute._addFileChildren(DashboardWorkspaceRouteChildren)

interface DashboardRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRouteWithChildren
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardProspectsRoute: typeof DashboardProspectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRouteWithChildren,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardProspectsRoute: DashboardProspectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  SignInRoute: SignInRoute,
  HandlerSplatRoute: HandlerSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
